-- 부서명을 입력 받아 같은 부서에 있는 사원의
-- 사원명, 부서명, 급여 조회
SELECT EMP_NAME, 
	NVL(DEPT_TITLE, '부서없음') AS DEPT_TITLE, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE NVL(DEPT_TITLE, '부서없음') = '인사관리부123' ;
;


--직급명, 급여를 입력 받아
--해당 직급에서 입력 받은 급여보다 많이 받는 사원의
--이름, 직급명, 급여, 연봉을 조회하여 출력

SELECT EMP_NAME, JOB_NAME, SALARY, SALARY * 12 ANNUAL_INCOME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE JOB_NAME = '대리'
AND SALARY > 2000000
;

-- 입사일을 입력("2022-09-06") 받아
-- 입력 받은 값 보다 먼저 입사한 사람의
-- 이름, 입사일(1990년 01월 01일), 성별(M,F) 조회

SELECT EMP_NAME 이름, 
	TO_CHAR(HIRE_DATE, 'YYYY"년" MM"월" DD"일"') 입사일, 
	DECODE( SUBSTR(EMP_NO, 8, 1) , '1', 'M', '2', 'F' ) 성별
FROM EMPLOYEE
WHERE HIRE_DATE < TO_DATE('2000-09-06')
;
					--> TO_DATE 생략 가능

-- 전체 사원 정보 조회
SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
	   NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
	   JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
;

-- 사번이 일치하는 사원 정보 조회
SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
	   NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
	   JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
WHERE EMP_ID = 200 ;


--주민등록번호가 일치하는 사원 정보 조회
SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
	   NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
	   JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
WHERE EMP_NO = '690402-2040612' ;

/*
'문자열'
1234 -- 숫자
"쌍따옴표 내부가 하나의 범위(문장)"
EMP_ID -- 테이블명, 컬럼명


*/


--입력 받은 부서와 일치하는 모든 사원 정보 조회 
SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
	   NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
	   JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
WHERE DEPT_TITLE = '인사관리부';


--입력 받은 급여 이상을 받는 모든 사원 정보 조회
SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
	   NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, 
	   JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
WHERE SALARY >= 2000000;	  


--부서별 급여 합 전체 조회
SELECT NVL(DEPT_CODE, '부서없음') DEPT_CODE, SUM(SALARY) TOTAL
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
GROUP BY DEPT_CODE
ORDER BY DEPT_CODE
;



-- 직급별 급여 평균 조회 
SELECT JOB_NAME, ROUND(AVG(SALARY), 1) AVERAGE
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
GROUP BY JOB_CODE, JOB_NAME
ORDER BY JOB_CODE
;







